# Supabase Local Development Config
# This file is used when running `supabase start` locally

project_id = "logistics-system"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false # Disable for local dev

[storage]
enabled = true
file_size_limit = "50MiB"

[functions]
enabled = true
verify_jwt = true
